const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';
const FETCH_PHOTOS_START = 'FETCH_PHOTOS_START';
const FETCH_PHOTOS_ERROR = 'FETCH_PHOTOS_ERROR';

export default {
    FETCH_PHOTOS_ERROR,
    FETCH_PHOTOS_START,
    FETCH_PHOTOS_SUCCESS
};
